tell me step by step how to configure a pipeline in jenkins to trigger on each push to the repository,set up the pipeline to execute the stages defined in the .gitlab-ci.yml file, configure the pipeline to execute on any branch and have the master branch deploy to the production environment,ensure  that the build stage installs the project dependencies by creating a file named requirements.txt with the following content:

Flask
pytest


The test stage should execute the unit tests by creating a file named test_app.py with the following content:

def test_devops_endpoint(client):
    response = client.post(
        '/DevOps',
        headers={'X-Parse-REST-API-Key': '2f5ae96c-b558-4c7b-a590-a501ae1c3f6c'},
        json={
            'message': 'This is a test',
            'to': 'Juan Perez',
            'from': 'Rita Asturia',
            'timeToLifeSec': 45
        }
    )
    assert response.status_code == 200
    assert response.json == {'message': 'Hello Juan Perez your message will be sent'}


