stages:
  - build
  - test
  - deploy

before_script:
  - apt-get update -qy
  - apt-get install -y python3-pip

build:
  stage: build
  script:
    - pip3 install -r requirements.txt

test:
  stage: test
  script:
    - echo "def test_devops_endpoint(client):
        response = client.post(
            '/DevOps',
            headers={'X-Parse-REST-API-Key': '2f5ae96c-b558-4c7b-a590-a501ae1c3f6c'},
            json={
                'message': 'This is a test',
                'to': 'Juan Perez',
                'from': 'Rita Asturia',
                'timeToLifeSec': 45
            }
        )
        assert response.status_code == 200
        assert response.json == {'message': 'Hello Juan Perez your message will be sent'}
    " > test_app.py
    - pytest test_app.py

deploy:
  stage: deploy
  script:
    - echo "Deploy to production environment"
  only:
    - master

